//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp44.UrunServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UrunDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UrunidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunAdField;
        
        private System.Nullable<short> UrunKategoriField;
        
        private System.Nullable<decimal> UrunFiyatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkaField;
        
        private System.Nullable<byte> StokField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Urunid {
            get {
                return this.UrunidField;
            }
            set {
                if ((this.UrunidField.Equals(value) != true)) {
                    this.UrunidField = value;
                    this.RaisePropertyChanged("Urunid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UrunAd {
            get {
                return this.UrunAdField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunAdField, value) != true)) {
                    this.UrunAdField = value;
                    this.RaisePropertyChanged("UrunAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<short> UrunKategori {
            get {
                return this.UrunKategoriField;
            }
            set {
                if ((this.UrunKategoriField.Equals(value) != true)) {
                    this.UrunKategoriField = value;
                    this.RaisePropertyChanged("UrunKategori");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<decimal> UrunFiyat {
            get {
                return this.UrunFiyatField;
            }
            set {
                if ((this.UrunFiyatField.Equals(value) != true)) {
                    this.UrunFiyatField = value;
                    this.RaisePropertyChanged("UrunFiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Marka {
            get {
                return this.MarkaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkaField, value) != true)) {
                    this.MarkaField = value;
                    this.RaisePropertyChanged("Marka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<byte> Stok {
            get {
                return this.StokField;
            }
            set {
                if ((this.StokField.Equals(value) != true)) {
                    this.StokField = value;
                    this.RaisePropertyChanged("Stok");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UrunServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsApp44.UrunServiceReference1.HelloWorldResponse HelloWorld(WindowsFormsApp44.UrunServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp44.UrunServiceReference1.HelloWorldResponse> HelloWorldAsync(WindowsFormsApp44.UrunServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name UrunlerListesiResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UrunlerListesi", ReplyAction="*")]
        WindowsFormsApp44.UrunServiceReference1.UrunlerListesiResponse UrunlerListesi(WindowsFormsApp44.UrunServiceReference1.UrunlerListesiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UrunlerListesi", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp44.UrunServiceReference1.UrunlerListesiResponse> UrunlerListesiAsync(WindowsFormsApp44.UrunServiceReference1.UrunlerListesiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp44.UrunServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsApp44.UrunServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp44.UrunServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsApp44.UrunServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UrunlerListesiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UrunlerListesi", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp44.UrunServiceReference1.UrunlerListesiRequestBody Body;
        
        public UrunlerListesiRequest() {
        }
        
        public UrunlerListesiRequest(WindowsFormsApp44.UrunServiceReference1.UrunlerListesiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UrunlerListesiRequestBody {
        
        public UrunlerListesiRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UrunlerListesiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UrunlerListesiResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp44.UrunServiceReference1.UrunlerListesiResponseBody Body;
        
        public UrunlerListesiResponse() {
        }
        
        public UrunlerListesiResponse(WindowsFormsApp44.UrunServiceReference1.UrunlerListesiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UrunlerListesiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<WindowsFormsApp44.UrunServiceReference1.UrunDTO> UrunlerListesiResult;
        
        public UrunlerListesiResponseBody() {
        }
        
        public UrunlerListesiResponseBody(System.Collections.Generic.List<WindowsFormsApp44.UrunServiceReference1.UrunDTO> UrunlerListesiResult) {
            this.UrunlerListesiResult = UrunlerListesiResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApp44.UrunServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApp44.UrunServiceReference1.WebService1Soap>, WindowsFormsApp44.UrunServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp44.UrunServiceReference1.HelloWorldResponse WindowsFormsApp44.UrunServiceReference1.WebService1Soap.HelloWorld(WindowsFormsApp44.UrunServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsApp44.UrunServiceReference1.HelloWorldRequest inValue = new WindowsFormsApp44.UrunServiceReference1.HelloWorldRequest();
            inValue.Body = new WindowsFormsApp44.UrunServiceReference1.HelloWorldRequestBody();
            WindowsFormsApp44.UrunServiceReference1.HelloWorldResponse retVal = ((WindowsFormsApp44.UrunServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp44.UrunServiceReference1.HelloWorldResponse> WindowsFormsApp44.UrunServiceReference1.WebService1Soap.HelloWorldAsync(WindowsFormsApp44.UrunServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp44.UrunServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsApp44.UrunServiceReference1.HelloWorldRequest inValue = new WindowsFormsApp44.UrunServiceReference1.HelloWorldRequest();
            inValue.Body = new WindowsFormsApp44.UrunServiceReference1.HelloWorldRequestBody();
            return ((WindowsFormsApp44.UrunServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp44.UrunServiceReference1.UrunlerListesiResponse WindowsFormsApp44.UrunServiceReference1.WebService1Soap.UrunlerListesi(WindowsFormsApp44.UrunServiceReference1.UrunlerListesiRequest request) {
            return base.Channel.UrunlerListesi(request);
        }
        
        public System.Collections.Generic.List<WindowsFormsApp44.UrunServiceReference1.UrunDTO> UrunlerListesi() {
            WindowsFormsApp44.UrunServiceReference1.UrunlerListesiRequest inValue = new WindowsFormsApp44.UrunServiceReference1.UrunlerListesiRequest();
            inValue.Body = new WindowsFormsApp44.UrunServiceReference1.UrunlerListesiRequestBody();
            WindowsFormsApp44.UrunServiceReference1.UrunlerListesiResponse retVal = ((WindowsFormsApp44.UrunServiceReference1.WebService1Soap)(this)).UrunlerListesi(inValue);
            return retVal.Body.UrunlerListesiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp44.UrunServiceReference1.UrunlerListesiResponse> WindowsFormsApp44.UrunServiceReference1.WebService1Soap.UrunlerListesiAsync(WindowsFormsApp44.UrunServiceReference1.UrunlerListesiRequest request) {
            return base.Channel.UrunlerListesiAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp44.UrunServiceReference1.UrunlerListesiResponse> UrunlerListesiAsync() {
            WindowsFormsApp44.UrunServiceReference1.UrunlerListesiRequest inValue = new WindowsFormsApp44.UrunServiceReference1.UrunlerListesiRequest();
            inValue.Body = new WindowsFormsApp44.UrunServiceReference1.UrunlerListesiRequestBody();
            return ((WindowsFormsApp44.UrunServiceReference1.WebService1Soap)(this)).UrunlerListesiAsync(inValue);
        }
    }
}
